version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"

  producer:
    build: ./producer
    image: producer

  consumer:
    build: ./consumer
    image: consumer

  zinc:
    image: public.ecr.aws/prabhat/zinc:latest
    ports:
      - "4080:4080" #webui
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=admin
      - DATA_PATH=/data
    user: 0:0